#server:
#  ssl:
#    enabled: true
#    key-store: classpath:localhost.p12
#    key-store-password: changeit
#    key-store-type: PKCS12
#    trust-store-type: PKCS12
#spring:
#  profiles: dev
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://localhost:8443/auth/realms/myrealm


---

server:
  ssl:
    enabled: false

spring:
  profiles: prod
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://recorder-hero.ca:8080/auth/realms/myrealm